apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
  annotations: {
    nginx.ingress.kubernetes.io/auth-type: 'basic',
    nginx.ingress.kubernetes.io/auth-secret: 'basic-auth',
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required',
spec:
  rules:
  - host: prom-alert.c2-n1.kube.int.komyr.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alertmanager-main
            port:
              name: web
