apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana-storage
  labels:
    kubernetes.io/namespace: monitoring
    app.kubernetes.io/name: grafana
spec:
  capacity:
    storage: 10Gi
  nfs:
    server: 10.1.10.1
    path: '/mnt/sto1-n1_ssd/komyr/int.komyr.com/kube/c2-n1/monitoring/grafana/storage'
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: monitoring-grafana-storage
  volumeMode: Filesystem
